config-version: 2

name: "brave_de_project"
version: "1.0.0"
require-dbt-version: ">=1.5.0"


profile: "my_dbt_project" # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
#seed-paths: [ "seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"

#seeds:
#  brave_de_project:
#    +schema: raw

models:
  brave_de_project:
    database: BRAVE_DATABASE
    schema: PROJECT_TEST
    raw_data:
      +materialized: table
    data_mart:
      +materialized: table
  +copy_grants: true
#
#tests:
#  +severity: warn  # all tests
